name: Generate Snake Animation 🐍

on:
  schedule:
    # Jalan otomatis setiap tengah malam (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch:  # Bisa dijalankan manual dari tab "Actions"
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Geraldoafrinandi   # GANTI dengan username GitHub kamu
          outputs: dist/snake.svg
          color_snake: "#00FFFF"
          color_dots: "#00FFAA,#00FFFF,#0077FF,#0F0"  # Warna neon cyberpunk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
